#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# #Lint test
npx lint-staged --concurrent false

#Check tsconfig standards
npm run check-types || {
    echo '😂🤮❌Failed Type check😂🤮❌
    Are you seriously trying to write that? Make the changes required above.'
    false;
}
#Check Prettier standards
npm run check-format || {
    echo '😂🤮Its Raw - Your styling looks disgusting😂🤮
    Prettier check Failed. Run npm run format, add changes and try commit again.'
    false;
}
#Check ESLint standards
npm run check-lint || {
    echo '😂🤮❌Get that weak Shit out there!😂🤮❌
    EsLint Check Failed. Make the required changes listed above, add changes and try commit again.'
    false;
}
#If every thing Passes.... try to run a build
    echo '😂... Alright... Code looks good to me.. Trying to build now. 😂'

npm run build || {
    echo '❌⚒️💡 Better call to your Senior... Because your build failed ❌⚒️💡
    Next build Failed: View the erros above to see why.'
    false
}
#If it build we can commit
    echo '✅✅✅ You win this time... I am commiting this now ✅✅✅'
